## 1. Elementwise Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [2]:
import numpy as np

In [3]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [9, 8,7 ]])

In [6]:
print(a) 
print()
print(b)

[[4 5 6]
 [5 7 9]]

[[1 2 3]
 [9 8 7]]


### Arithmetic Operations

In [4]:
a + b # np.add()

array([[ 5,  7,  9],
       [14, 15, 16]])

In [7]:
a - b # np.subtract()

array([[ 3,  3,  3],
       [-4, -1,  2]])

In [8]:
a * b # np.multiply

array([[ 4, 10, 18],
       [45, 56, 63]])

In [9]:
a ** 2 # np.square , np.power()

array([[16, 25, 36],
       [25, 49, 81]])

In [11]:
a % 3 # np.divmod()

array([[1, 2, 0],
       [2, 1, 0]])

In [13]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

### Trignometric

In [19]:
new = 1 / np.sin(a)
print(new)

[[-1.32134871 -1.04283521 -3.57889955]
 [-1.04283521  1.52210106  2.42648664]]


In [16]:
1 / np.tan(b)

array([[ 0.64209262, -0.45765755, -7.01525255],
       [-2.21084541, -0.14706506,  1.14751542]])

### Rounding operations

In [18]:
np.round(new)

array([[-1., -1., -4.],
       [-1.,  2.,  2.]])

In [20]:
np.around(new, 2)

array([[-1.32, -1.04, -3.58],
       [-1.04,  1.52,  2.43]])

In [24]:
np.fix(new)

array([[-1., -1., -3.],
       [-1.,  1.,  2.]])

In [23]:
np.floor(new)

array([[-2., -2., -4.],
       [-2.,  1.,  2.]])

### Exponential Functions

In [26]:
np.exp(a)

array([[  54.59815003,  148.4131591 ,  403.42879349],
       [ 148.4131591 , 1096.63315843, 8103.08392758]])

In [27]:
np.log(b)

array([[0.        , 0.69314718, 1.09861229],
       [2.19722458, 2.07944154, 1.94591015]])

## 2. Matrix Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [28]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


In [31]:
print(a) 
print()
print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [29]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [34]:
np.transpose(b)

array([[5, 7],
       [6, 8]])

In [38]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [39]:
np.trace(a)

np.int64(5)

In [40]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [43]:
# A . A-1 = I
np.dot(
    a, np.linalg.inv(a)
).round()

array([[1., 0.],
       [0., 1.]])

In [44]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [45]:
# Solve Equations: x + 2*y = 1 and 3*x + 5*y = 2
a = [[1, 2], [3, 5]]
b = [1, 2]
print('Solution to the Equations is:', np.linalg.solve(a, b))

Solution to the Equations is: [-1.  1.]
