## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `np.concatenate()`: Method to concatenate two or more arrays
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low = 10, high = 50, size = (5,2,3))
arr

array([[[33, 24, 36],
        [31, 30, 29]],

       [[49, 10, 11],
        [27, 36, 36]],

       [[36, 10, 11],
        [49, 29, 14]],

       [[21, 35, 34],
        [48, 44, 23]],

       [[37, 23, 24],
        [21, 10, 45]]])

In [3]:
arr.shape

(5, 2, 3)

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr.ndim

3

In [6]:
arr.T

array([[[33, 49, 36, 21, 37],
        [31, 27, 49, 48, 21]],

       [[24, 10, 10, 35, 23],
        [30, 36, 29, 44, 10]],

       [[36, 11, 11, 34, 24],
        [29, 36, 14, 23, 45]]])

In [7]:
new_arr = arr.reshape((3,5,2))
new_arr.shape

(3, 5, 2)

In [8]:
flat_arr = new_arr.flatten()
flat_arr.shape

(30,)

In [9]:
arr.sum()

np.int64(866)

In [10]:
arr.sum(axis = 0)

array([[176, 102, 116],
       [176, 149, 147]])

In [11]:
arr.max()

np.int64(49)

In [12]:
arr.max(axis = 1)

array([[33, 30, 36],
       [49, 36, 36],
       [49, 29, 14],
       [48, 44, 34],
       [37, 23, 45]])

## 0 > column wise
## 1 > row wise

In [13]:
lsr3 = [[40, 40, 45],
       [44, 18, 47],
       [17, 40, 46]]
arr3 = np.array(lsr3)

In [14]:
arr3

array([[40, 40, 45],
       [44, 18, 47],
       [17, 40, 46]])

In [15]:
arr3.max()

np.int64(47)

In [16]:
arr3.prod(axis =1)

array([72000, 37224, 31280])

In [17]:
arr3.argmax(axis = 1)

array([2, 2, 2])

In [20]:
arr3

array([[40, 40, 45],
       [44, 18, 47],
       [17, 40, 46]])

In [21]:
arr3.cumsum(axis = 1)

array([[ 40,  80, 125],
       [ 44,  62, 109],
       [ 17,  57, 103]])

In [37]:
arr1 = np.random.randint(low = 10, high = 50, size = (2,3))
arr11 = np.random.randint(low = 10, high = 50, size = (2,3))


In [38]:
arr1 , arr11

(array([[48, 48, 10],
        [39, 28, 47]]),
 array([[43, 42, 44],
        [16, 41, 25]]))

In [39]:
np.vstack((arr1, arr11))

array([[48, 48, 10],
       [39, 28, 47],
       [43, 42, 44],
       [16, 41, 25]])

In [40]:
np.hstack((arr1, arr11))

array([[48, 48, 10, 43, 42, 44],
       [39, 28, 47, 16, 41, 25]])