In [1]:
import numpy as np

## Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

### Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.

- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

**OR**

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]


 ### Slicing:

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [2]:
# 1D Array -> Similar to list
a = np.array([1,5,3,7])

In [4]:
print(a[0])

1


In [6]:
print(a[1::2])

[5 7]


In [23]:
# 2D Array > Similar to matrix
list2 = [
    [2,5,7, 5],
    [4, 9,11, 55],
    [64, 6,34, 99],
    [64, 6,34, 33]
    
]
array2 = np.array(list2)
array2

array([[ 2,  5,  7,  5],
       [ 4,  9, 11, 55],
       [64,  6, 34, 99],
       [64,  6, 34, 33]])

In [24]:
print(array2[1][2])

11


In [25]:
array2.shape

(4, 4)

In [30]:
# print(array2[<row_slice>, <col_slice>])
print(array2[::2, 1:3])

[[ 5  7]
 [ 6 34]]


In [31]:
# ND Array
random_array = np.random.randint(low = 10, high = 50, size = (2,3,4))

In [32]:
print(random_array)

[[[17 28 17 46]
  [14 43 27 33]
  [35 14 43 15]]

 [[31 35 29 15]
  [27 22 10 24]
  [44 25 25 16]]]


In [36]:
# Find element : 1st Matrix , 2x2 element
print(random_array[0,2,2])

43


In [38]:
print(random_array[::2,:3,:4])

[[[17 28 17 46]
  [14 43 27 33]
  [35 14 43 15]]]


In [49]:
print(random_array[-1, 0:-2, 1:])

[[35 29 15]]


In [51]:
random_array1 = np.random.randint(low = 10, high = 50, size = (10,16,8))
print(random_array1.shape)

(10, 16, 8)


In [55]:
random_array1[4:5,:4]

array([[[43, 41, 30, 20, 21, 20, 47, 44],
        [49, 26, 46, 32, 43, 45, 31, 20],
        [12, 12, 32, 45, 31, 32, 24, 43],
        [36, 39, 16, 45, 44, 10, 38, 42]]])

### Boolean or Mask Indexing:

Boolean or mask indexing is a powerful feature in NumPy that allows you to use boolean arrays (or masks) to select elements from another array. The basic idea behind boolean indexing is to create a boolean array with the same shape as the array you want to select from, where each element of the boolean array corresponds to whether or not you want to select the corresponding element from the other array.

In [57]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [72]:
mask = a < 4
mask

array([[ True,  True],
       [ True, False],
       [False, False]])

In [67]:
print(a[mask])

[1 2 3]


In [70]:
a = np.array([[1, 2], [3, 4], [5, 6]])
mask = np.array([True, False, True])
print(a)
print(mask)

[[1 2]
 [3 4]
 [5 6]]
[ True False  True]


In [71]:
a[mask]

array([[1, 2],
       [5, 6]])