## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `np.concatenate()`: Method to concatenate two or more arrays
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low = 10, high = 50, size = (5,2,3))
arr

array([[[40, 14, 21],
        [39, 40, 45]],

       [[17, 18, 47],
        [44, 13, 11]],

       [[17, 40, 30],
        [17, 32, 46]],

       [[11, 26, 27],
        [44, 37, 22]],

       [[40, 17, 22],
        [48, 49, 23]]])

In [30]:
arr.shape

(5, 2, 3)

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr.ndim

3

In [9]:
arr.T

array([[[40, 17, 17, 11, 40],
        [39, 44, 17, 44, 48]],

       [[14, 18, 40, 26, 17],
        [40, 13, 32, 37, 49]],

       [[21, 47, 30, 27, 22],
        [45, 11, 46, 22, 23]]])

In [29]:
new_arr = arr.reshape((3,5,2))
new_arr.shape

(3, 5, 2)

In [35]:
flat_arr = new_arr.flatten()
flat_arr.shape

(30,)

In [43]:
arr.sum()

np.int64(897)

In [48]:
arr.sum(axis = 0)

array([[125, 115, 147],
       [192, 171, 147]])

In [42]:
arr.max()

np.int64(49)

In [46]:
arr.max(axis = 1)

array([[40, 40, 45],
       [44, 18, 47],
       [17, 40, 46],
       [44, 37, 27],
       [48, 49, 23]])

## 0 > column wise
## 1 > row wise

In [51]:
lsr3 = [[40, 40, 45],
       [44, 18, 47],
       [17, 40, 46]]
arr3 = np.array(lsr3)

In [53]:
arr3

array([[40, 40, 45],
       [44, 18, 47],
       [17, 40, 46]])

In [62]:
arr3.max()

np.int64(47)

In [64]:
arr3.prod(axis =1)

array([72000, 37224, 31280])

In [69]:
arr3.argmax(axis = 0)

array([1, 0, 1])