In [4]:
!pip install numpy

  Using cached numpy-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)


In [5]:
import numpy as np

## Creating Numpy Array

In [15]:
list1 = [2,4,5]

array = np.array(list1)

In [16]:
print(type(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
1
(3,)


In [18]:
list2 = [
            [1,5,9],
            [6,8,2]
        ]

array2 = np.array(list2)

In [21]:
print(array2)
print(array2.ndim)
print(array2.shape)

[[1 5 9]
 [6 8 2]]
2
(2, 3)


In [39]:
array2.dtype

dtype('int64')

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [40]:
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [41]:
zero.dtype

dtype('float64')

In [23]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [31]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
print(np.eye(N=4, M= 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [33]:
print(np.random.rand(2,3))

[[0.87210061 0.26905036 0.6706653 ]
 [0.29669792 0.49745734 0.98677196]]


In [44]:
list(range(5,55,5))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [38]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [48]:
np.arange(-6.3,13.6,2.67)

array([-6.3 , -3.63, -0.96,  1.71,  4.38,  7.05,  9.72, 12.39])

In [45]:
# np.linspace(start, stop, no_element) > linear space

array_linspace1 = np.linspace(start=0, stop=10, num=5)
print(array_linspace1)

[ 0.   2.5  5.   7.5 10. ]


In [50]:
array_linspace1 = np.linspace(start=(0,0,0), stop=(10,20,30), num=5, axis=1)
print(array_linspace1)

[[ 0.   2.5  5.   7.5 10. ]
 [ 0.   5.  10.  15.  20. ]
 [ 0.   7.5 15.  22.5 30. ]]


In [55]:
diag_array = np.diag([3,6,3,6])
diag_array

array([[3, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 6]])

In [74]:

nDarray = np.random.randint(low = 4, high=34, size = (2,3,2,2))

In [75]:
nDarray.shape

(2, 3, 2, 2)

In [76]:
nDarray

array([[[[30, 18],
         [ 4, 14]],

        [[ 9, 10],
         [32, 26]],

        [[19, 18],
         [25, 30]]],


       [[[ 6, 13],
         [ 6, 15]],

        [[31,  4],
         [15, 10]],

        [[15, 27],
         [16, 21]]]])